// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class Calendario
{
    public int Idcalendario { get; set; }

    public DateOnly? Fecha { get; set; }

    public string Descripcion { get; set; }
}