// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

/// <summary>
/// Calendario de pagos por cuotas de cada préstamo
/// </summary>
public partial class CalendarioPago
{
    public int Id { get; set; }

    public int IdPrestamo { get; set; }

    public int NumeroCuota { get; set; }

    public DateOnly FechaProgramada { get; set; }

    public DateOnly? FechaPagoReal { get; set; }

    public decimal MontoCuota { get; set; }

    public decimal? MontoPagado { get; set; }

    public decimal? Capital { get; set; }

    public decimal? Interes { get; set; }

    public decimal? Mora { get; set; }

    public string Estado { get; set; }

    public int? DiasMora { get; set; }

    public string Observaciones { get; set; }

    public int CreadoPor { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public decimal? Domicilio { get; set; }

    public virtual Login CreadoPorNavigation { get; set; }

    public virtual Prestamo IdPrestamoNavigation { get; set; }
}