// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class Cliente
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Dui { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public DateOnly? FechaIngreso { get; set; }

    public string Departamento { get; set; }

    public sbyte? Activo { get; set; }

    public string Giro { get; set; }

    public string Referencia1 { get; set; }

    public string Telref1 { get; set; }

    public string Referencia2 { get; set; }

    public string Telref2 { get; set; }

    public int? Idgestor { get; set; }

    public string TipoPer { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public string Nit { get; set; }

    public string Sexo { get; set; }

    public string DuiFrente { get; set; }

    public string DuiDetras { get; set; }

    public string Fotonegocio1 { get; set; }

    public string Fotonegocio2 { get; set; }

    public string Fotonegocio3 { get; set; }

    public string Fotonegocio4 { get; set; }

    public decimal? Longitud { get; set; }

    public decimal? Latitud { get; set; }

    public string Profesion { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Prestamo> Prestamos { get; set; } = new List<Prestamo>();
}