// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class Eliminadoshistorico
{
    public int Id { get; set; }

    public int Idprestamo { get; set; }

    public DateOnly? FechaPago { get; set; }

    public int? Numeropago { get; set; }

    public decimal? Monto { get; set; }

    public sbyte? Pagado { get; set; }

    public DateOnly? FechaCouta { get; set; }

    public decimal? Capital { get; set; }

    public decimal? Interes { get; set; }

    public decimal? Mora { get; set; }

    public decimal? Morahist { get; set; }
}