// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class Gestor
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public int? Departamento { get; set; }

    public sbyte? Activo { get; set; }

    public int? Idpuesto { get; set; }

    public int? Idusuario { get; set; }
}