// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class Infored
{
    public int Id { get; set; }

    public int? Año { get; set; }

    public int? Mes { get; set; }

    public string Nombre { get; set; }

    public string TipoPer { get; set; }

    public int? NumPtmo { get; set; }

    public string Inst { get; set; }

    public string FecOtor { get; set; }

    public decimal? Monto { get; set; }

    public decimal? Plazo { get; set; }

    public decimal? Saldo { get; set; }

    public decimal? Mora { get; set; }

    public int? FormaPag { get; set; }

    public int? TipoRel { get; set; }

    public string LineaCre { get; set; }

    public int? Dias { get; set; }

    public DateOnly? UltPag { get; set; }

    public string TipoGar { get; set; }

    public int? TipoMon { get; set; }

    public decimal? Valcuota { get; set; }

    public int? Dia { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public string Dui { get; set; }

    public string Nit { get; set; }

    public DateOnly? FechaCancelado { get; set; }

    public DateOnly? Diasvencido { get; set; }

    public int? NumCoutas { get; set; }

    public string CalifAct { get; set; }

    public string ActiviEco { get; set; }

    public string Sexo { get; set; }

    public int? Estado { get; set; }
}