// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class Login
{
    public int Id { get; set; }

    public string Usuario { get; set; }

    public string Password { get; set; }

    public ulong? Activo { get; set; }

    public virtual ICollection<CalendarioPago> CalendarioPagos { get; set; } = new List<CalendarioPago>();
}