// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class Pagosdetalle
{
    public int Id { get; set; }

    public int Idprestamo { get; set; }

    public DateOnly? FechaPago { get; set; }

    public int? Numeropago { get; set; }

    public decimal? Monto { get; set; }

    public sbyte? Pagado { get; set; }

    public DateOnly? FechaCouta { get; set; }

    public decimal? Capital { get; set; }

    public decimal? Interes { get; set; }

    public decimal? Mora { get; set; }

    public decimal? Morahist { get; set; }

    public string TipoPago { get; set; }

    public int? CreadoPor { get; set; }

    /// <summary>
    /// COBRO, DESEMBOLSO
    /// </summary>
    public string TipoMovimiento { get; set; }

    /// <summary>
    /// ID del préstamo relacionado
    /// </summary>
    public int? ReferenciaPrestamo { get; set; }

    public string ObservacionesMovimiento { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public ulong? CorteCaja { get; set; }

    public decimal? Domicilio { get; set; }

    public virtual Prestamo IdprestamoNavigation { get; set; }
}