// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class Permiso
{
    public int Id { get; set; }

    public string Modulo { get; set; }

    public string Permiso1 { get; set; }
}