// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class Prestamo
{
    public int Id { get; set; }

    public int? Idcliente { get; set; }

    public DateOnly? Fecha { get; set; }

    public decimal? Monto { get; set; }

    public decimal? Tasa { get; set; }

    public int? NumCoutas { get; set; }

    public decimal? Cuota { get; set; }

    public decimal? Interes { get; set; }

    public DateOnly? ProximoPago { get; set; }

    public string Estado { get; set; }

    public DateOnly? FechaCancelado { get; set; }

    public string TipoPrestamo { get; set; }

    public ulong? Aprobado { get; set; }

    public int? CreadaPor { get; set; }

    public DateOnly? FechaCreadafecha { get; set; }

    public decimal? TasaDomicilio { get; set; }

    public decimal? Domicilio { get; set; }

    public string DetalleAprobado { get; set; }

    public string Observaciones { get; set; }

    public string DetalleRechazo { get; set; }

    public DateOnly? FechaRechazado { get; set; }

    public int? RechazadoPor { get; set; }

    public DateOnly? FechaAprobacion { get; set; }

    public int? AprobadoPor { get; set; }

    public DateOnly? FechaReenvio { get; set; }

    public int? ReenviadoPor { get; set; }

    public virtual ICollection<CalendarioPago> CalendarioPagos { get; set; } = new List<CalendarioPago>();

    public virtual Cliente IdclienteNavigation { get; set; }

    public virtual ICollection<Pagosdetalle> Pagosdetalles { get; set; } = new List<Pagosdetalle>();
}