// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class Puesto
{
    public int Id { get; set; }

    public string Nombre { get; set; }
}