// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class PuestoPermiso
{
    public int Id { get; set; }

    public int PuestoId { get; set; }

    public int PermisoId { get; set; }

    public ulong Activo { get; set; }
}