// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Credi_Express.Models;

public partial class VistaPagosCompletum
{
    public int Id { get; set; }

    public int IdPrestamo { get; set; }

    public int NumeroCuota { get; set; }

    public DateOnly FechaProgramada { get; set; }

    public DateOnly? FechaPagoReal { get; set; }

    public decimal MontoCuota { get; set; }

    public decimal? MontoPagado { get; set; }

    public decimal? Capital { get; set; }

    public decimal? Interes { get; set; }

    public decimal? Mora { get; set; }

    public string Estado { get; set; }

    public int? DiasMora { get; set; }

    public string Observaciones { get; set; }

    public int? Idcliente { get; set; }

    public decimal? MontoPrestamo { get; set; }

    public decimal? Tasa { get; set; }

    public int? NumCoutas { get; set; }

    public string TipoPrestamo { get; set; }

    public string NombreCliente { get; set; }

    public string Dui { get; set; }

    public string Telefono { get; set; }

    public string Celular { get; set; }

    public string NombreGestor { get; set; }

    public int? DiasVencimientoCalculado { get; set; }

    public string TipoDia { get; set; }
}